version: 2

updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      2023.1-chi:
        patterns: ["2023.1/*"]
      ussuri-kvm:
        patterns: ["ussuri-kvm/*"]
