version: 2

updates:
  - package-ecosystem: gitsubmodule
    directories:
      - "/"
    schedule:
      interval: "daily"
    groups:
      2023.1-chi:
        patterns: ["2023.1-chi*"]
      ussuri-kvm:
        patterns: ["ussuri-kvm*"]
